csgo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
urlpatterns = [
    path('',include('stats.urls')),
    path('store/',include('store.urls')),
    path('academy-admin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
    path('__debug__/', include(debug_toolbar.urls)),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

stats/urls.py
from django.urls import path
from . import views

app_name = 'stats'

urlpatterns = [
    path('',views.Index.as_view(),name='index'),
    path('servers/',views.ServerView.as_view(),name='servers'),
    path('premium/',views.VipListView.as_view(),name='premium'),
    # path('stats/<str:db>/',views.ServerStatsView.as_view(),name='staticstics'),
    path('profile/<int:steamid64>/',views.ProfileView.as_view(),name='profile'),
    path('misc/report-player/',views.ReportView.as_view(),name='report'),
    path('misc/appeal-ban/',views.AppealView.as_view(),name='appeal'),
    path('misc/contact/',views.ContactView.as_view(),name='contact'),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.PremiumStore.as_view(),name='index'),
    path('checkout/<slug:slug>/<str:steamid>/', views.CheckoutView.as_view(),name='checkout'),
    path('checkout-stripe/<slug:slug>/<str:steamid>/', views.StripeCheckoutView.as_view(),name='checkout_stripe'),
    path('checkout-stripe-done/', views.StripeCheckoutDoneView.as_view(),name='checkout_stripe_done'),
    path('checkout-khalti/<slug:slug>/<str:steamid>/',views.KhaltiCheckoutView.as_view(),name='checkout_khalti'),
    path('checkout-khalti-done/',views.KhaltiCheckoutDoneView.as_view(),name='checkout_khalti_done'),
    path('verify/', views.KhaltiVerifyView.as_view(),name='khalti_verification_url')
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
    integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
  <script src="https://khalti.s3.ap-south-1.amazonaws.com/KPG/dist/2020.12.17.0.0.0/khalti-checkout.iffe.js"></script>
  <!-- <link rel="stylesheet" href="{% static 'server/css/notiflix.css' %}"> -->
  <link rel="stylesheet" href="{% static 'server/css/server.css' %}">

  <title>IT Creative Academy</title>
  <script src="{% static 'server/js/notiflix-aio-2.7.0.min.js' %}"></script>

</head>

<body style="height: 100%;">
  <script>
      Notiflix.Report.Init({
        'className':'notiflix-report',
        'backgroundColor':'#31373f',
        'borderRadius':'10px',
        'messageColor':'#cbcbcb',
        'plainText':false,
        'buttonBackground':'#fddc20',
        'buttonColor':'#000',
        success: {
          'buttonBackground':'#fddc20',
          'buttonColor':'#000',
          'svgColor':'#fddc20',
          'titleColor':'#cbcbcb',
          'messageColor':'#cbcbcb',
          'backgroundColor':'#31373f',
          'backOverlayColor':'rgba(0, 0, 0, 0.5)',},
        
      });
        Notiflix.Notify.Init({
      'position':'center-top',
      'timeout':4000,
      'clickToClose':true
    });
  </script>
  <style>
    .notiflix-report-button,.notiflix-report-button a{
        text-decoration: none;
    }
</style>
  {% with usersteamid=user.get_steamid %}
  <!-- Sidebar -->
  <div class="sidebar">
    <div class="sidebar-brand d-flex my-4">
      <a href="{% url 'stats:index' %}" class="m-auto">
        <img src="{% static 'logo.png' %}" alt="AG" class="m-auto" width="180px">
      </a>
    </div>
    <ul class="nav flex-column" id="nav-sidebar">
      <li class="nav-item">
        <div class="nav-link" href="#">
          <button class="btn btn-outline-danger me-auto d-md-none" id="sidebar-toggle-close">X</button>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{% url 'stats:index' %}">
          <span class="round-icon"><i class="fas fa-home"></i></span><span class="icon-text">Bosh saxifa</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{% url 'stats:servers' %}">
          <span class="round-icon"><i class="fas fa-server"></i></span><span class="icon-text">Ariza yozish</span>
        </a>
      </li>
      <li class="nav-item header">
        Imkoniyatlar
      </li>
      <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{% url 'stats:premium' %}">
          <span class="round-icon"><i class="fas fa-crown"></i></span><span class="icon-text">Maxsus paket</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{% url 'store:index' %}">
          <span class="round-icon"><i class="fas fa-store"></i></span><span class="icon-text">Admin bilan aloqa</span>
        </a>
      </li>
      <li class="nav-item header">
        
      </li>
      {% for s in servers_list %}
        {% if s.stats_db_url %}
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'stats:staticstics' s.display_name %}">
            <div class="round-icon"><i class="{{s.icon}}"></i></div>
            <div class="icon-text">{{s.display_name | capfirst }}</div>
          </a>
        </li>
        {% endif %}
      {% endfor %}
      <li class="nav-item header">
        MISC
      </li>
      <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{% url 'stats:report' %}">
          <div class="round-icon"><i class="fas fa-clipboard-check"></i></div>
          <div class="icon-text"></div>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{% url 'stats:appeal' %}">
          <span class="round-icon"><i class="fas fa-ban"></i></span><span class="icon-text">Appeal Ban</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{% url 'stats:contact' %}">
          <span class="round-icon"><i class="fas fa-address-book"></i></span><span class="icon-text">Contact Us</span>
        </a>
      </li>
      <li class="nav-item" style="display: none;">
        <a class="nav-link" aria-current="page" href="/profile/">
          <span class="round-icon"><i class="fas fa-address-book"></i></span><span class="icon-text">Contact Us</span>
        </a>
      </li>
    </ul>
  </div>

  <!-- Main Content -->
  <div class="content">
    <button class="btn btn-outline-secondary me-auto d-md-none"
      style="position: absolute;left: 0;top: 0;margin-top: 25px;margin-left: 10px;" id="sidebar-toggle-open">
      <i class="fas fa-bars"></i>
    </button>
    {% if user.is_authenticated %}
    {% if usersteamid %}
    <a class="login-button btn btn-outline-light ms-auto me-3 " href="{% url 'stats:profile' usersteamid.uid %}"
      style="position: absolute;right: 0;top: 0;margin-top: 25px;">
      <img style="border-radius: 25px;" src="{{usersteamid.extra_data.player.avatarfull}}" width="25px" alt="PP">
      {{user.username}}
      {% else %}
      <a class="btn btn-outline-light ms-auto me-3 login-button" href="#"
        style="position: absolute;right: 0;top: 0;margin-top: 25px;">
        <i class="fas fa-tools"></i>
        {{user.username}}
        {% endif %}
      </a>
      {% else %}
      <a class="btn btn-outline-light ms-auto me-3 login-button" href="{% url 'social:begin' 'steam' %}"
        style="position: absolute;right: 0;top: 0;margin-top: 25px;">
        <i class="fas fa-sign-in-alt"></i>
        Login
      </a>
      {% endif %}

      {% block content %}
      {% endblock content %}

  </div>


  <!-- BS JS  -->

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.0-rc.1/dist/js.cookie.min.js"></script>
  <script src="{% static 'server/js/server.js' %}"></script>

  {% block js %}
  {% endblock js %}
  {% endwith %}


  <script>
    // Sidebar expand logic
    $('#sidebar-toggle-close').click(function () {
      $('.sidebar').hide('show');
      $('.sidebar').removeClass('open');
      $('body').removeClass('overflow-hidden');
    });
    $('#sidebar-toggle-open').click(function () {
      $('.sidebar').show('open');
      $('body').addClass('overflow-hidden');
    });

  </script>
  <script>
    Notiflix.Notify.Init({
      'position':'center-top',
      'timeout':4000,
      'clickToClose':true
    });

    {% if messages %}
      {% for message in messages %}
        Notiflix.Notify.{{ message.extra_tags | capfirst }}('{{message}}');
      {% endfor %}
    {% endif %}
  </script>

</body>



</html>

templates/footer.html
{% load static %}
<div class="mt-auto footer" style="background-image: url({% static 'footer-particle.png' %});background-size: cover;background-position: top;">
    <div class="footer-header text-center">
        <h3 style="color: var(--icon-text-active);font-weight: bold;">
            ABOUT ACADEMY GAMING
        </h3>
        <p>
            Delivering the very best gameplay experience with one of the most friendly and non-toxic community.
        </p>
    </div>
    <div class="d-flex justify-content-around text-center mt-3 flex-wrap" style="text-transform: uppercase;">
        <div>
            <h5>3+</h5>
            <h6>Community Servers</h6>
        </div>
        <div>
            <h5>5+</h5>
            <h6>Tournaments Sponsored</h6>
        </div>
        <div>
            <h5>1000+</h5>
            <h6>Active Players</h6>
        </div>
        <div>
            <h5>10+</h5>
            <h6>Staffs</h6>
        </div>
        <div>
            <h5>100+</h5>
            <h6>Servers hosted</h6>
        </div>
    </div>
    <hr>
    <p class="text-center m-0">Hand Crafted by <a href="https://github.com/prajwalbasnet4400" target="_blank" class="text-decoration-none">TheOnionKnight</a> with ☕ & 🤍 / Design by <a href="https://steamcommunity.com/id/-unl0cky-/" target="_blank" class="text-decoration-none">unl0cky</a></p>

</div>

templates/index.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
<style>
  #heading{text-shadow: 0 0 1px #fff, 0 0 20px #fff, 0 0 30px #f3ff4d00, 0 0 35px #f3ff4d00, 0 0 40px #f3ff4d, 0 0 45px #f3ff4d00, 0 0 50px #f3ff4d00;}      
</style>

<div class="container-fluid p-0" style="background-image: url({% static 'landing-min.jpg' %});background-repeat: no-repeat;background-size: cover;background-position: center;">
  <div>
    <div class="landing d-flex flex-column">
      <div class="mx-auto mt-auto text-center pb-5" style="color: var(--icon-text-hover);">
        <h5 id="pre-heading" style="display: none;color: #fff;">WELCOME TO</h5>
        <h1 class="display-4" id="heading" style="font-weight: 600;">Academy Gaming</h1>
        <h6 style="color: var(--icon-text-active);display: none;" id="suf-heading">Counter Strike : Global Offensive</h6>
        <a class="btn btn-outline-primary" href="https://discord.com/invite/academygaming" target="_blank" id="join-us" style="display: none;">Join Us</a>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block js %}
<script>
    $('#pre-heading').slideDown(500);
    $('#suf-heading').show(1000);
    $('#join-us').slideDown(1500);
</script>
{% endblock js %}

templates/test.html
<html>
<head>
    <script src="https://khalti.s3.ap-south-1.amazonaws.com/KPG/dist/2020.12.17.0.0.0/khalti-checkout.iffe.js"></script>
</head>
<body>
    ...
    <!-- Place this where you need payment button -->
    <button id="payment-button">Pay with Khalti</button>
    <!-- Place this where you need payment button -->
    <!-- Paste this code anywhere in you body tag -->
    <script>
        var config = {
            // replace the publicKey with yours
            "publicKey": "test_public_key_e86f56d334834564af5af94c65fe2dfa",
            "productIdentity": "1234567890",
            "productName": "Dragon",
            "productUrl": "http://gameofthrones.wikia.com/wiki/Dragons",
            "paymentPreference": [
                "KHALTI",
                "EBANKING",
                "MOBILE_BANKING",
                "CONNECT_IPS",
                "SCT",
                ],
            "eventHandler": {
                onSuccess (payload) {
                    // hit merchant api for initiating verfication
                    console.log(payload);
                },
                onError (error) {
                    console.log(error);
                },
                onClose () {
                    console.log('widget is closing');
                }
            }
        };

        var checkout = new KhaltiCheckout(config);
        var btn = document.getElementById("payment-button");
        btn.onclick = function () {
            // minimum transaction amount must be 10, i.e 1000 in paisa.
            checkout.show({amount: 1000});
        }
    </script>
    <!-- Paste this code anywhere in you body tag -->
    ...
</body>
</html>