csgo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
urlpatterns = [
    path('',include('stats.urls')),
    path('store/',include('store.urls')),
    path('academy-admin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
    path('__debug__/', include(debug_toolbar.urls)),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

stats/urls.py
from django.urls import path
from . import views

app_name = 'stats'

urlpatterns = [
    path('',views.Index.as_view(),name='index'),
    path('servers/',views.ServerView.as_view(),name='servers'),
    path('premium/',views.VipListView.as_view(),name='premium'),
    # path('stats/<str:db>/',views.ServerStatsView.as_view(),name='staticstics'),
    path('profile/<int:steamid64>/',views.ProfileView.as_view(),name='profile'),
    path('misc/report-player/',views.ReportView.as_view(),name='report'),
    path('misc/appeal-ban/',views.AppealView.as_view(),name='appeal'),
    path('misc/contact/',views.ContactView.as_view(),name='contact'),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.PremiumStore.as_view(),name='index'),
    path('checkout/<slug:slug>/<str:steamid>/', views.CheckoutView.as_view(),name='checkout'),
    path('checkout-stripe/<slug:slug>/<str:steamid>/', views.StripeCheckoutView.as_view(),name='checkout_stripe'),
    path('checkout-stripe-done/', views.StripeCheckoutDoneView.as_view(),name='checkout_stripe_done'),
    path('checkout-khalti/<slug:slug>/<str:steamid>/',views.KhaltiCheckoutView.as_view(),name='checkout_khalti'),
    path('checkout-khalti-done/',views.KhaltiCheckoutDoneView.as_view(),name='checkout_khalti_done'),
    path('verify/', views.KhaltiVerifyView.as_view(),name='khalti_verification_url')
]

store/models.py
from django.db import models
from django.utils.text import slugify

from stats.models import Server

class Product(models.Model):
    class MethodChoices(models.TextChoices):
            KHALTI = "KHALTI", "KHALTI"
            STRIPE = "STRIPE", "STRIPE"
    title = models.CharField(max_length=64)
    price = models.PositiveIntegerField(help_text='Enter in paisa. ie Rs 10 is 1000')
    server = models.ForeignKey(Server,on_delete=models.SET_NULL,null=True,related_name='products')
    duration = models.PositiveSmallIntegerField()
    slug = models.SlugField(unique=True,blank=True)
    payment_method = models.CharField(max_length=64,choices=MethodChoices.choices,default=MethodChoices.KHALTI)

    def __str__(self):
        return self.title

    def save(self,*args, **kwargs):
        slug = f"{self.server.display_name}-{self.duration}D"
        self.slug = slugify(slug)
        super().save(*args, **kwargs)
    
    def in_stock(self):
        return self.server.product_in_stock()
    
    def f_price(self):
        return self.price // 100

class Purchase(models.Model):
    """
        DEPRECATED.
        Only kept to not delete old purchase records
    """
    buyer = models.CharField(max_length=54,null=True)
    receiver = models.CharField(max_length=54,null=True)
    idx = models.CharField(max_length=128)
    product = models.ForeignKey(Product,on_delete=models.SET_NULL,null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)

    def __str__(self):
        return self.idx

class StripePurchase(models.Model):
    buyer = models.CharField(max_length=54,null=True)
    receiver = models.CharField(max_length=54,null=True)
    idx = models.CharField(max_length=128)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)

    def __str__(self):
        return self.idx

class KhaltiPurchase(models.Model):
    buyer = models.CharField(max_length=54,null=True)
    receiver = models.CharField(max_length=54,null=True)
    idx = models.CharField(max_length=128)
    pidx = models.CharField(max_length=128)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)

    def __str__(self):
        return self.idx

store/views.py
from django.conf import settings
from django.shortcuts import get_object_or_404, redirect
from django.http.response import HttpResponse
from django.views.generic import View, ListView, DetailView
from django.contrib import messages
from django.http import Http404
from django.urls import reverse
import stripe
from django.utils.decorators import method_decorator
from stats.models import Vip
from store.models import StripePurchase
from stats.models import Server
from stats.resolver import get_playerinfo,get_steamid
from django.views.decorators.csrf import csrf_exempt
from .models import Product
from .logic import premium,khalti

stripe.api_key = settings.STRIPE_SK

class PremiumStore(ListView):
    template_name = 'store/premium_store.html'
    queryset = Server.objects.filter(selling_premium=True)
    context_object_name = 'servers'
    
    def post(self,request,*args, **kwargs):
        try:
            steamid = get_playerinfo(request.POST.get('steamid'))
        except:
            messages.add_message(request,messages.ERROR,'Error Fetching SteamID',extra_tags='Failure')
            return redirect('store:index')
        if not steamid:
            messages.add_message(request,messages.ERROR,'Error Fetching SteamID',extra_tags='Failure')
            return redirect('store:index')
        product = request.POST.get('product','error')
        return redirect('store:checkout',slug=product,steamid=steamid.get('steamid','error'))    

class CheckoutView(DetailView):
    template_name = 'store/checkout.html'
    model = Product
    context_object_name = 'product'
    
    def dispatch(self, request, *args, **kwargs):
        obj = get_object_or_404(self.model,slug=kwargs.get('slug'))
        steamid64 = kwargs.get('steamid')
        if not obj.in_stock():
            vip = Vip.objects.filter(steamid64=steamid64,server=obj.server)
            if not vip.exists():
                messages.add_message(self.request,messages.INFO,'Product Out Of Stock','Failure')
                return redirect('store:index')
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        steamid = self.kwargs.get('steamid')
        context['profile'] = get_playerinfo(steamid)
        return context
    

class KhaltiVerifyView(View):
    """
        Deprecated
    """
    url = 'https://khalti.com/api/v2/payment/verify/'

    def post(self,request,*args, **kwargs):
        data = request.POST
        product_pk = data.get('product_identity')
        product = Product.objects.get(slug=product_pk)
        
        if not product.in_stock():
            return HttpResponse(status=400)

        response = khalti.verify_khalti(token=data.get('token'),amount=data.get('amount'))


        if not response.get('success'):                                     # If the provided token is invalid return HTTP 400
            return HttpResponse(status=400)

        profile = get_playerinfo(data.get('merchant_extra'))
        if request.user.is_authenticated:
            premium.add_vip(response['data']['product_identity'],response['data']['idx'],
                            get_steamid(profile['steamid']),profile['steamid'],profile['personaname'],profile['avatarfull'],**{'buyer':request.user})
        else:
            premium.add_vip(response['data']['product_identity'],response['data']['idx'],
                            get_steamid(profile['steamid']),profile['steamid'],profile['personaname'],profile['avatarfull'])
            
        return HttpResponse(status=200)
class StripeCheckoutView(View):
    def post(self, *args, **kwargs):
        product = self.get_object(self.kwargs.get("slug"))
        steamid = self.kwargs.get("steamid")
        checkout_session = stripe.checkout.Session.create(
            line_items=[
                {
                    'price_data': {
                        'currency':'USD',
                        'product_data':{
                            'name':product.title,
                        },
                        'unit_amount':product.price
                    },
                    'quantity': 1,
                },
            ],
            client_reference_id=steamid,
            metadata={'slug':product.slug},
            mode='payment',
            success_url=settings.SITE_URL + reverse("store:checkout_stripe_done"),
            cancel_url=settings.SITE_URL + reverse("store:checkout",args=[product.slug,steamid]),
        )
        return redirect(checkout_session.url, code=303)

    def get_object(self, slug):
        product = Product.objects.filter(slug=slug).first()
        if not product:
            print("Product not found {}".format(slug))
            raise Http404()
        return product

@method_decorator(csrf_exempt,"dispatch")
class StripeCheckoutDoneView(View):

    def get(self,*args,**kwargs):
        messages.success(self.request,"Premium purchase successful","success")
        return redirect("stats:premium")
    
    def post(self,*args,**kwargs):
        payload = self.request.body
        sig_header = self.request.META['HTTP_STRIPE_SIGNATURE']
        event = None

        try:
            event = stripe.Webhook.construct_event(
            payload, sig_header, settings.STRIPE_WH_SECRET
            )
        except ValueError as e:
            # Invalid payload
            return HttpResponse(status=400)
        except stripe.error.SignatureVerificationError as e:
            # Invalid signature
            return HttpResponse(status=400)

        id = event['data']['object']['payment_intent']
        # Check if a duplicate request
        if StripePurchase.objects.filter(idx=id).exists():
            return HttpResponse(status=400)

        if event['type'] == 'checkout.session.completed':
            # Retrieve the session. If you require line items in the response, you may include them by expanding line_items.
            session = stripe.checkout.Session.retrieve(
            event['data']['object']['id'],
            expand=['line_items'],
            )
            profile = get_playerinfo(session.client_reference_id)
            product_slug = session.metadata['slug']
            if self.request.user.is_authenticated:
                premium.add_vip(product_slug,id,
                                get_steamid(profile['steamid']),profile['steamid'],profile['personaname'],profile['avatarfull'],**{'buyer':self.request.user})
            else:
                premium.add_vip(product_slug,id,
                                get_steamid(profile['steamid']),profile['steamid'],profile['personaname'],profile['avatarfull'])

        return HttpResponse(status=200)

class KhaltiCheckoutView(View):
    def get(self,*args,**kwargs):
        product_slug = self.kwargs.get("slug")
        steamid = self.kwargs.get("steamid")
        product = Product.objects.filter(slug=product_slug).first()
        pidx, payment_url = khalti.KhaltiV2.initiate_payment(product.price,steamid,product.slug)
        return redirect(payment_url)

class KhaltiCheckoutDoneView(View):

    def get(self, *args, **kwargs):
        params = self.request.GET
        try:
            pidx = params['pidx']
            product_slug = params['purchase_order_name']
            steamid = params['purchase_order_id']
            tidx = params['transaction_id']
        except Exception as e:
            raise e

        resp = khalti.KhaltiV2.verify_payment(pidx)
        print(resp)
        if resp.get('success'):
            profile = get_playerinfo(steamid)
            if self.request.user.is_authenticated:
                premium.add_vip(product_slug,tidx,
                                get_steamid(profile['steamid']),profile['steamid'],profile['personaname'],
                                profile['avatarfull'],**{'buyer':self.request.user,'pidx':pidx})
            else:
                premium.add_vip(product_slug,tidx,
                                get_steamid(profile['steamid']),profile['steamid'],profile['personaname'],profile['avatarfull'],**{'pidx':pidx})
            messages.success(self.request,"Premium purchase successful","success")
            return redirect("stats:premium")
        else:
            messages.error(self.request,"Premium purchase failed. Please contact an admin for further info","failure")
            return redirect("store:index")

templates/store/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid" style="padding-top:80px;font-family: 'Open Sans';">
    {% csrf_token %}
    <div class="row">
        <h1 style="font-family: 'Raleway';font-size: 2.3rem;">PURCHASE DETAILS</h1>

        <div class="col-12 col-md-4">
            <div class="mx-auto" style="border: none;">
                <p>
                <div class="custom-form">
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label></label>Username:</label>
                                <input disabled type="text" value="{{profile.personaname}}" class="form-control">
                            </div>
                            <div class="form-group">
                                <label></label>SteamID:</label>
                                <input disabled type="text" value="{{profile.steamid}}" class="form-control">
                            </div>
                        </div>
                        <div class="col d-flex">
                            <img class="mt-auto" src="{{profile.avatarfull}}" width="128px" alt="PP">
                        </div>
                    </div>
                    <div class="form-group">
                        <label></label>Profile URL:</label>
                        <a target="_blank" href="{{profile.profileurl}}"
                            style="text-decoration: none;background-color: #31373f60;color: #cbcbcb;border: none;font-size: 0.9rem;"
                            class="form-control">{{profile.profileurl}}</a>
                    </div>
                    <div class="form-group">
                        <label></label>Server:</label>
                        <input disabled type="text" value="{{product.server}}" class="form-control">
                    </div>
                    <div class="form-group">
                        <label></label>Duration:</label>
                        <input disabled type="text" value="{{product.duration}} days" class="form-control">
                    </div>
                    <div class="form-group">
                        <label></label>Price:</label>
                        <input disabled type="text" value="{% if product.payment_method == 'STRIPE' %}$ {% else %}Rs {% endif %}{{product.f_price}}" class="form-control">
                    </div>
                </div>
                </p>
            </div>
        </div>
        <div class="col-12 col-md-8">
            <div class="card mx-auto server-card" style="border: none;max-width: 350px;">
                <img src="{% static 'logo.png' %}" width="200px" alt="" class="mx-auto">
                <h4 style="font-family:'Gilroy-Bold';margin-top: 0.5rem;" class="theme-color text-center">
                    {{product.server}}</h4>
                <hr class="theme-color" style="height: 1.5px;opacity: 1;">
                <ul class="list-group bg-transparent" style="text-align: left;">
                    <li class="list-group-item" style="color: #cbcbcb;font-size: 0.9rem;font-weight: bold;"><i
                            class="fas fa-check theme-color me-1"></i> Reserved slot</li>
                    <li class="list-group-item" style="color: #cbcbcb;font-size: 0.9rem;font-weight: bold;"><i
                            class="fas fa-check theme-color me-1"></i> SKINCHANGER (!ws,!knife)</li>
                    <li class="list-group-item" style="color: #cbcbcb;font-size: 0.9rem;font-weight: bold;"><i
                            class="fas fa-check theme-color me-1"></i> PREMIUM tag</li>
                    <li class="list-group-item" style="color: #cbcbcb;font-size: 0.9rem;font-weight: bold;"><i
                            class="fas fa-check theme-color me-1"></i> Priority support</li>
                    <li class="list-group-item" style="color: #cbcbcb;font-size: 0.9rem;font-weight: bold;"><i
                            class="fas fa-check theme-color me-1"></i> Server moderation</li>
                </ul>
                {% if product.payment_method == "STRIPE" %}
                    <form class="d-flex justify-content-evenly my-3" action="{% url 'store:checkout_stripe' product.slug profile.steamid %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn theme-btn" id="checkout-button">Checkout with Stripe</button>
                    </form>
                {% elif product.payment_method == "KHALTI" %}
                    <form class="d-flex justify-content-evenly my-3" action="{% url 'store:checkout_khalti' product.slug profile.steamid %}" method="GET">
                        <button type="submit" class="btn theme-btn" id="checkout-button">Checkout with Khalti</button>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% include 'footer.html' %}
{% endblock content %}

templates/store/premium_store.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="container-fluid" style="padding-top:80px;font-family: 'Raleway';">
  <div class="my-3">

    <div class="row">
      {% for server in servers %}
      <div class="col-12 col-md-6 text-center d-flex flex-column theme-color p-2">
        <div class="card mx-auto server-card" style="border: none;min-width: 25vw;">
          <img src="{% static 'logo.png' %}" width="200px" alt="" class="mx-auto">
          <h4 style="font-family:'Gilroy-Bold';margin-top: 0.5rem;">{{server}}</h4>
          <hr style="height: 1.5px;opacity: 1;">
          <ul class="list-group bg-transparent" style="text-align: left;">
            <li class="list-group-item" style="color: #cbcbcb;font-size: 0.9rem;font-weight: bold;"><i
                class="fas fa-check theme-color me-1"></i> Reserved slot</li>
            <li class="list-group-item" style="color: #cbcbcb;font-size: 0.9rem;font-weight: bold;"><i
                class="fas fa-check theme-color me-1"></i> SKINCHANGER (!ws,!knife)</li>
            <li class="list-group-item" style="color: #cbcbcb;font-size: 0.9rem;font-weight: bold;"><i
                class="fas fa-check theme-color me-1"></i> PREMIUM tag</li>
            <li class="list-group-item" style="color: #cbcbcb;font-size: 0.9rem;font-weight: bold;"><i
                class="fas fa-check theme-color me-1"></i> Priority support</li>
            <li class="list-group-item" style="color: #cbcbcb;font-size: 0.9rem;font-weight: bold;"><i
                class="fas fa-check theme-color me-1"></i> Server moderation</li>
          </ul>
          <div class="d-flex justify-content-evenly my-3">
            {% for product in server.products.all %}
            <button type="button" class="btn theme-btn" data-bs-toggle="modal" data-bs-target="#productModal"
              data-bs-product="Premium - {{product.title}} Server ({{product.duration}} days)"
              data-bs-url="{{product.slug}}"><i class="fas fa-cart-plus"></i> {{product.duration}} days</button>
              {% endfor %}
              
            </div>
            {% if not server.product_in_stock %}
              Out of stock // Renew available
            {% endif %}
        </div>
      </div>
      {% endfor %}
      <div class="col-12">
        <div class="d-flex flex-row justify-content-center my-5 text-center">
          <div class="m-5 flex-fill ">
              <h5 class="theme-color text-uppercase" style="font-weight: bold;">GOT BANNED FROM OUR SERVER?</h5>
              <p>Did something wrong and got banned from our servers?<br>
                Appeal for unban to get a chance to play in our servers again.                
              </p>
              <a href="{% url 'stats:appeal' %}" class="btn btn-sm theme-btn">Explore Now</a>
          </div>
          <div class="" style="min-height: 50px;width: 2px;background-color: #31373f;border-radius: 25px;"></div>
          <div class="m-5 flex-fill ">
              <h5 class="theme-color text-uppercase" style="font-weight: bold;">ANYTHING WRONG HAPPENED?</h5>
              <p>
                Did anyone do anything against rule in our servers?<br>
                Report the user and help us punish the users that like breaking rules.                
              </p>
              <a href="{% url 'stats:report' %}" class="btn btn-sm theme-btn">Explore Now</a>
  
          </div>
      </div>
      </div>
    </div>
  </div>
</div>


<div class="modal fade " data-bs-backdrop="static" id="productModal" tabindex="-1" aria-labelledby="productModalLabel"
aria-hidden="true">
<div class="modal-dialog modal-dialog-centered " id="no-blue">
  <div class="modal-content checkout-modal">
    <div class="modal-header" style="border-bottom: 1px solid #cbcbcb70;">
      <h5 class="modal-title" id="productModalLabel">TITLE</h5>
      <button type="button" class="btn text-secondary" data-bs-dismiss="modal" aria-label="Close"><i class="fas fa-times"></i></button>
    </div>
    <div class="modal-body">
      <form id="checkout-form" method="POST" autocomplete="off">
{% csrf_token %}

        <div class="mb-3">
          <label for="message-text" class="col-form-label">Steam Profile URL:</label>
          <input type="text" id="product-id" name="product" value="" style="display: none;">
          <input name="steamid" id="steam-id" class="form-control" style="background: #212529;color: #cbcbcb;font-size: 0.9rem;border: none;"
            value="http://steamcommunity.com/profiles/{{usersteamid.uid}}"></input>
          <div id="steamid-help" class="form-text">{% if user.is_authenticated %}Prefilled with you steamID. {% endif %}Don't worry, we will verify the steamID in the next page.</div>
        </div>
      </form>
    </div>
    <div class="modal-footer" style="border-top: 1px solid #cbcbcb71;">
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      <input type="submit" id="submit-checkout" form="checkout-form" class="btn theme-btn" 
        value="Proceed"></input>
    </div>
  </div>
</div>
</div>


<style>
  #no-blue input:focus,#no-blue button:focus,#no-blue button:focus-within , #no-blue input:focus-within{
    outline: none;
    box-shadow: none;
  }
</style>

{% include 'footer.html' %}
{% endblock content %}

{% block js %}
<script>
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
  var productModal = document.getElementById('productModal')
  productModal.addEventListener('show.bs.modal', function (event) {
    // Button that triggered the modal
    var button = event.relatedTarget
    // Extract info from data-bs-* attributes
    var product = button.getAttribute('data-bs-product')
    var url = button.getAttribute('data-bs-url')
    console.log(url)
    // Update the modal's content.
    var modalTitle = productModal.querySelector('.modal-title')
    var modalForm = productModal.querySelector('#product-id')

    modalTitle.textContent = product
    modalForm.setAttribute('value',url)
  });
</script>
{% endblock js %}

templates/store/product.html
{% extends 'base.html' %}
{% block content %}
{% load markdownify %}
{% csrf_token %}

<div class="container-fluid" style="padding-top:80px;font-family: 'Open Sans';">
  <div class="d-flex">
    <div>
      
      {{products.first.title}}
      <p>
        {{products.first.features | markdownify }}
      </p>
    </div>
    <div>
      {% for product in products %}
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#productModal"
        data-bs-product="{{product.title}} for {{product.duration}} days"
        data-bs-url="{% url 'store:checkout' product.slug %}">Buy {{product.duration}}</button>
      {% endfor %}

    </div>
  </div>

  <div class="modal fade " data-bs-backdrop="static" id="productModal" tabindex="-1" aria-labelledby="productModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered ">
      <div class="modal-content checkout-modal">
        <div class="modal-header">
          <h5 class="modal-title" id="productModalLabel">TITLE</h5>
          <button type="button" class="btn btn-close text-primary" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form id="checkout-form" method="GET" autocomplete="off">
            <div class="mb-3">
              <label for="message-text" class="col-form-label">Steam profile url:</label>
              <input name="steamid" id="steam-id" class="form-control"
                value="http://steamcommunity.com/profiles/{{user.get_steamid}}"></input>
              <div id="steamid-help" class="form-text">Prefilled with you steamid.Don't worry, we will verify the
                steamid in the next page</div>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <input type="submit" id="submit-checkout" form="checkout-form" class="btn btn-primary"
            value="Proceed to checkout"></input>
        </div>
      </div>
    </div>
  </div>


</div>
{% include 'footer.html' %}
{% endblock content %}

{% block js %}
<script>
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
  var productModal = document.getElementById('productModal')
  productModal.addEventListener('show.bs.modal', function (event) {
    // Button that triggered the modal
    var button = event.relatedTarget
    // Extract info from data-bs-* attributes
    var product = button.getAttribute('data-bs-product')
    var url = button.getAttribute('data-bs-url')
    // Update the modal's content.
    var modalTitle = productModal.querySelector('.modal-title')
    var modalForm = productModal.querySelector('#checkout-form')

    modalTitle.textContent = product
    modalForm.setAttribute('action', url)
  })
  $('#submit-checkout').click(function (e) {
    e.preventDefault();
    form = $('#checkout-form');
    steamid = $('#steam-id');
    payload = { 'steamid': steamid.val() }
    $.ajax({
      type: "POST",
      url: '',
      data: payload,
      dataType: 'json',
      headers: { 'X-CSRFToken': csrftoken },
      statusCode: {
        200: function (data) {
          steamid.val(data.steamid)
          form.submit()
        }
      }
    });

  });
</script>
{% endblock js %}